# Generated by Django 6.0 on 2026-01-02 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0002_remove_user_profile_picture_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardtracker',
            name='team',
        ),
        migrations.AddField(
            model_name='rewardtracker',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reward_tracker', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
