# Generated by Django 6.0 on 2026-01-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0003_remove_rewardtracker_team_rewardtracker_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookings_since_reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_bookings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_rewards_claimed',
            field=models.IntegerField(default=0),
        ),
    ]
