# Generated by Django 6.0 on 2026-01-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0006_alter_team_options_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
