# Generated by Django 6.0 on 2026-01-18 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0007_team_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(max_length=100, unique=True)),
                ('time_slot_ids', models.JSONField()),
                ('ground_id', models.IntegerField()),
                ('pidx', models.CharField(max_length=200)),
                ('total_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pending_bookings',
            },
        ),
        migrations.DeleteModel(
            name='RewardTracker',
        ),
    ]
